# _config.yml
title: What Joe Watch
description: Just a girl who loves watching tv shows and movies and sharing my thoughts on them!
url: https://whatjoewatch.com
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-feed
  - jekyll-include-cache

main:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
  - title: Movies
    url: /movies/
  - title: TV
    url: /tv/
  - title: Weekend Wrapup
    url: /ww/

header:
  nav: true

category_archive:
  type: liquid
  path: /categories/